version: '3'
services:
  jekyll:
    build: devsart:latest
    command: /bin/sh -c "npm run build && bundle exec jekyll s -H 0.0.0.0"
    volumes:
      - .:/devsart
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=production
  nginx:
    image: nginx
    links:
      - jekyll
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ~/config/cert.pem:/etc/ssl/certs/cert.pem
      - ~/config/key.pem:/etc/ssl/private/key.pem
      - ./tmp/cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
