version: '3'
services:
  jekyll:
    image: devsart:latest
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=production
      - TZ=Asia/Bangkok
  nginx:
    image: nginx
    links:
      - jekyll
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ~/config/cert.pem:/etc/ssl/certs/cert.pem
      - ~/config/key.pem:/etc/ssl/private/key.pem
      - ./tmp/cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Bangkok      
