version: '3'
services:
  jekyll:
    build: .
    command: /bin/sh -c "bundle exec jekyll s -H 0.0.0.0"
    volumes:
      - .:/devsart
    ports:
      - "4000:4000"
  nginx:
    image: nginx
    links:
      - jekyll
    volumes:
      - ./public:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/jekyll.conf:ro
      # - ./config/cert.pem:/etc/ssl/certs/cert.pem:ro
      # - ./config/key.pem:/etc/ssl/private/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
