version: '3'
services:
  jekyll:
    build: .
    command: /bin/sh -c "bundle exec jekyll s -H 0.0.0.0"
    volumes:
      - .:/devsart
    ports:
      - "4000:4000"
  nginx:
    image: nginx
    links:
      - jekyll
    volumes:
      - ./config/htpasswd:/etc/nginx/htpasswd
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/csr/0000_csr-certbot.pem:/etc/ssl/certs/cert.pem
      - /etc/letsencrypt/key/0000_key-certbot.pem:/etc/ssl/private/key.pem
    ports:
      - "80:80"
      - "443:443"
